cc_library(
    name="capture_engine",
    srcs=[
        "capture_engine.hpp",
    ],
    visibility=["//visibility:public"],
)

cc_library(
    name="frame",
    srcs=[
        "frame.cpp",
        "frame.hpp",
    ],
    visibility=["//visibility:public"],
)
