py_binary(
    name = "clang_format",
    srcs = [
        "lint.py"
    ],
    main = "lint.py",
    args = [
        "--lint-executable='clang-format'",
    ],
    deps = [
        "//tools:print",
    ],
)
