load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "print",
    srcs = [
        "print.py"
    ],
    deps = [
        requirement("termcolor"),
    ],
    visibility = ["//visibility:public"],
)
