name: Code Format Check
run-name: Format evaluation on ${{ github.ref }} with ${{ github.sha }}
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  validate_format:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Check Code Format
        run: bazel run format
