name: Code Lint
run-name: Lint evaluation for ${{ vars.GITHUB_SHA }}

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Run lint
        run: bazel run //tools/lint:clang_format
